name: Daily Market Analysis

on:
  schedule:
    - cron: '0 12 * * 1-5'  # 12 PM UTC, Mon-Fri
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4
      
      - name: Set up Python
        uses: actions/setup-python@v5  # Updated to v5
        with:
          python-version: '3.11'
      
      - name: Cache dependencies
        uses: actions/cache@v4  # Updated to v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas numpy requests python-dateutil PyYAML pandas_ta ta finnhub-pytho newsapi-python lxml beautifulsoup4 scikit-learn vaderSentiment aiohttp asyncio-throttle google-generativeai html5lib
      
      - name: Run analysis and send email
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: python main.py --output email
