name: Daily Market Report

on:
  schedule:
    - cron: "0 14 * * *"   # Runs daily at 14:00 UTC
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/twopirllc/pandas-ta.git
          pip install pandas yfinance requests beautifulsoup4 openai matplotlib ta

      - name: Run daily market report
        env:
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          ALPHAVANTAGE_KEY: ${{ secrets.ALPHAVANTAGE_KEY }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          python main.py --output email
